### ISSUE TITLE
Query on use of COPP module's TRAP event for filtering/receiving EAPOL packets at control plane

### ISSUE THREAD

**Issue by thovikeerthi** [sonic-net/sonic-swss#2563]
Hi Team,
We have a requirement to receive EAPOL traffic at SONiC's control plane handling. To receive this EAPOL traffic, do we need to set/register COPP module based TRAP events ?
If not, what is the other option available to receive this EAPOL traffic. Please suggest.

**Comment by prsunny** [comment]
You would have to create TRAP for such traffic. Try adding to this file to your local build and verify - https://github.com/sonic-net/sonic-buildimage/blob/master/files/image_config/copp/copp_cfg.j2

**Comment by thovikeerthi** [comment]
Hi Sunny,
Thanks for the update. 
I tried this approach by adding this file as part of my local build and also able to view it at path '/etc/sonic/' in the target/board. But, corresponding COPP's TRAP configuration is not updated in the config_db.json file (although I started copp-config.service). 
Please advice, what is missing in my steps to set these configs in config_db.json and enable EAPOL traffic .

**Comment by thovikeerthi** [comment]
Hi, I could see that, eapol traffic trap is already registered/used by macsec feature. So, can I register another control plane instance as well to receive EAPOL traffic ? 
How would EAPOL traffic be distributed from ASIC ? i.e. will it be a common notification to all control plane observers who are listening for it ? or only registered observers will get it?
Please advice.
